-- For creating the Happy 2022 table. I based the values/atributes on the 'Cantril Self-Anchoring Striving Scale (Cantril, 1965).' ID is created automatically. I didn't include a 'CHECK FOR JSON' constraint, since POST will always be coming through as a {key:value} pair from the HTML <form>. And I believe (I'll have to doublecheck) that Flask has the Jsonify library to hand outgoing JSON. 

CREATE TABLE HAPPY2022 (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ladder_present NUMBER,
    ladder_future NUMBER
); 